### ISSUE TITLE
It doesn't recognize some of the clans.

### ISSUE THREAD

**Issue by 2-bithacker** [AngrySnout/SauerTracker#10]
I noticed NOT all the existing clans are in the clan list.  Why?

**Comment by sauerbraten** [comment]
Send a pull request to add the clans you think are missing: https://github.com/AngrySnout/SauerTracker/blob/master/vars.json

There are some conditions though: https://github.com/AngrySnout/SauerTracker/wiki/FAQ#how-can-i-have-my-clan-added-to-the-trackers-clan-list-for-clanwar-detection-server-browser--etc

**Comment by 2-bithacker** [comment]
Pull request made.  The RD Clan has for sure been around more than 15 days, and has more than 2 members.  As for the spring clan I've seen spring members all over the place for weeks.

**Comment by AngrySnout** [comment]
I will not be adding RD| to the clan list.

**Comment by 2-bithacker** [comment]
fine

**Comment by 2-bithacker** [comment]
Why?
