### ISSUE TITLE
Original Colors in descriptionStyled

### ISSUE THREAD

**Issue by SalatielSauer** [AngrySnout/SauerTracker#5]
Hi, this is more a style suggestion than an issue...
Since descriptionStyled returns the server description and the colors, how about putting exactly the same color values ​​as the ones from Sauer?

![descriptionStyled](https://user-images.githubusercontent.com/9287152/58279710-7e974800-7d75-11e9-84ac-b63e2cdd820a.gif)
Small change, but I think it will be more readable :D.

```
#40ff80 green
#60a0ff blue
#ffc040 yellow
#ff4040 red
#808080 grey
#c040c0 purple
#ff8000 orange
```

**Comment by AngrySnout** [comment]
Added in 8d87f3cbb6517b4f4d192a528ee884ff2f2991f4.
